# Basys3 constraints for MicroBlaze AXI4-Lite SoC
# Source top-level wrapper:
# vivado/basys3/microblaze_axi_soc/microblaze_axi_soc.gen/sources_1/bd/microblaze_axi_soc_bd/hdl/microblaze_axi_soc_bd_wrapper.v
# Vivado target: 2020.2, part xc7a35tcpg236-1

## Clock: Basys3 100 MHz oscillator
set_property PACKAGE_PIN W5 [get_ports {clk_100mhz_i}]
set_property IOSTANDARD LVCMOS33 [get_ports {clk_100mhz_i}]
create_clock -name clk_100mhz_i -period 10.000 [get_ports {clk_100mhz_i}]

## System reset v2: external PMOD JA4/G2 active-low reset with pull-up
## Vivado 2020.2 rejected the earlier CPU_RESETN/C12 assignment for part xc7a35tcpg236-1.
## Wiring model: JA4 signal -> push button -> GND, not pressed=1, pressed=0.
set_property PACKAGE_PIN G2 [get_ports {reset_i}]
set_property IOSTANDARD LVCMOS33 [get_ports {reset_i}]
set_property PULLUP true [get_ports {reset_i}]

## USB-UART bridge
set_property PACKAGE_PIN B18 [get_ports {uart_rxd_i}]
set_property IOSTANDARD LVCMOS33 [get_ports {uart_rxd_i}]
set_property PACKAGE_PIN A18 [get_ports {uart_txd_o}]
set_property IOSTANDARD LVCMOS33 [get_ports {uart_txd_o}]

## Switches
set_property PACKAGE_PIN V17 [get_ports {sw_i[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[0]}]
set_property PACKAGE_PIN V16 [get_ports {sw_i[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[1]}]
set_property PACKAGE_PIN W16 [get_ports {sw_i[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[2]}]
set_property PACKAGE_PIN W17 [get_ports {sw_i[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[3]}]
set_property PACKAGE_PIN W15 [get_ports {sw_i[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[4]}]
set_property PACKAGE_PIN V15 [get_ports {sw_i[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[5]}]
set_property PACKAGE_PIN W14 [get_ports {sw_i[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[6]}]
set_property PACKAGE_PIN W13 [get_ports {sw_i[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[7]}]
set_property PACKAGE_PIN V2 [get_ports {sw_i[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[8]}]
set_property PACKAGE_PIN T3 [get_ports {sw_i[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[9]}]
set_property PACKAGE_PIN T2 [get_ports {sw_i[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[10]}]
set_property PACKAGE_PIN R3 [get_ports {sw_i[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[11]}]
set_property PACKAGE_PIN W2 [get_ports {sw_i[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[12]}]
set_property PACKAGE_PIN U1 [get_ports {sw_i[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[13]}]
set_property PACKAGE_PIN T1 [get_ports {sw_i[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[14]}]
set_property PACKAGE_PIN R2 [get_ports {sw_i[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[15]}]

## LEDs
set_property PACKAGE_PIN U16 [get_ports {led_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[0]}]
set_property PACKAGE_PIN E19 [get_ports {led_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[1]}]
set_property PACKAGE_PIN U19 [get_ports {led_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[2]}]
set_property PACKAGE_PIN V19 [get_ports {led_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[3]}]
set_property PACKAGE_PIN W18 [get_ports {led_o[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[4]}]
set_property PACKAGE_PIN U15 [get_ports {led_o[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[5]}]
set_property PACKAGE_PIN U14 [get_ports {led_o[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[6]}]
set_property PACKAGE_PIN V14 [get_ports {led_o[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[7]}]
set_property PACKAGE_PIN V13 [get_ports {led_o[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[8]}]
set_property PACKAGE_PIN V3 [get_ports {led_o[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[9]}]
set_property PACKAGE_PIN W3 [get_ports {led_o[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[10]}]
set_property PACKAGE_PIN U3 [get_ports {led_o[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[11]}]
set_property PACKAGE_PIN P3 [get_ports {led_o[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[12]}]
set_property PACKAGE_PIN N3 [get_ports {led_o[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[13]}]
set_property PACKAGE_PIN P1 [get_ports {led_o[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[14]}]
set_property PACKAGE_PIN L1 [get_ports {led_o[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[15]}]

## GPIO push buttons, kept separate from CPU_RESETN
set_property PACKAGE_PIN U18 [get_ports {btn_i[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn_i[0]}]
set_property PACKAGE_PIN T18 [get_ports {btn_i[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn_i[1]}]
set_property PACKAGE_PIN W19 [get_ports {btn_i[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn_i[2]}]
set_property PACKAGE_PIN T17 [get_ports {btn_i[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn_i[3]}]
set_property PACKAGE_PIN U17 [get_ports {btn_i[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn_i[4]}]

## Seven-segment display segment bus: CA, CB, CC, CD, CE, CF, CG, DP
set_property PACKAGE_PIN W7 [get_ports {fnd_data_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fnd_data_o[0]}]
set_property PACKAGE_PIN W6 [get_ports {fnd_data_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fnd_data_o[1]}]
set_property PACKAGE_PIN U8 [get_ports {fnd_data_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fnd_data_o[2]}]
set_property PACKAGE_PIN V8 [get_ports {fnd_data_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fnd_data_o[3]}]
set_property PACKAGE_PIN U5 [get_ports {fnd_data_o[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fnd_data_o[4]}]
set_property PACKAGE_PIN V5 [get_ports {fnd_data_o[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fnd_data_o[5]}]
set_property PACKAGE_PIN U7 [get_ports {fnd_data_o[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fnd_data_o[6]}]
set_property PACKAGE_PIN V7 [get_ports {fnd_data_o[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fnd_data_o[7]}]

## Seven-segment display digit enables: AN0..AN3
set_property PACKAGE_PIN U2 [get_ports {fnd_com_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fnd_com_o[0]}]
set_property PACKAGE_PIN U4 [get_ports {fnd_com_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fnd_com_o[1]}]
set_property PACKAGE_PIN V4 [get_ports {fnd_com_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fnd_com_o[2]}]
set_property PACKAGE_PIN W4 [get_ports {fnd_com_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fnd_com_o[3]}]

## PMOD JA: provisional Sensor mapping
set_property PACKAGE_PIN J1 [get_ports {sr04_trig_o}]
set_property IOSTANDARD LVCMOS33 [get_ports {sr04_trig_o}]
set_property PACKAGE_PIN L2 [get_ports {sr04_echo_i}]
set_property IOSTANDARD LVCMOS33 [get_ports {sr04_echo_i}]
set_property PACKAGE_PIN J2 [get_ports {dht11_io}]
set_property IOSTANDARD LVCMOS33 [get_ports {dht11_io}]
set_property PULLUP true [get_ports {dht11_io}]

## PMOD JB: provisional SPI mapping
set_property PACKAGE_PIN A14 [get_ports {spi_sclk_o}]
set_property IOSTANDARD LVCMOS33 [get_ports {spi_sclk_o}]
set_property PACKAGE_PIN A16 [get_ports {spi_mosi_o}]
set_property IOSTANDARD LVCMOS33 [get_ports {spi_mosi_o}]
set_property PACKAGE_PIN B15 [get_ports {spi_miso_i}]
set_property IOSTANDARD LVCMOS33 [get_ports {spi_miso_i}]
set_property PACKAGE_PIN B16 [get_ports {spi_ss_n_o}]
set_property IOSTANDARD LVCMOS33 [get_ports {spi_ss_n_o}]

## PMOD JC: provisional I2C mapping
set_property PACKAGE_PIN K17 [get_ports {i2c_scl_io}]
set_property IOSTANDARD LVCMOS33 [get_ports {i2c_scl_io}]
set_property PULLUP true [get_ports {i2c_scl_io}]
set_property PACKAGE_PIN M18 [get_ports {i2c_sda_io}]
set_property IOSTANDARD LVCMOS33 [get_ports {i2c_sda_io}]
set_property PULLUP true [get_ports {i2c_sda_io}]


